name: 'Automerge Dependabot PRs'

on:
  workflow_call:

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata ğŸ¤–
        id: dependabot_metadata
        uses: dependabot/fetch-metadata@v1.3.6
        with:
          github-token: ${{ secrets.DEPENDABOT_TOKEN }}

      - name: Authenticate CLI with PAT ğŸ”
        run: echo "${{ secrets.DEPENDABOT_TOKEN }}" | gh auth login --with-token

      - name: Enable auto-merge for Dependabot PRs ğŸ•º
        if: steps.dependabot_metadata.outputs.dependency-type == 'direct:development' && (steps.dependabot_metadata.outputs.update-type == 'version-update:semver-minor' || steps.dependabot_metadata.outputs.update-type == 'version-update:semver-patch')
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
