name: 'Automerge Dependabot PRs'

on:
  workflow_call:
    secrets:
      token:
        description: 'needed for login'
        required: false

jobs:
  dependabot:
    runs-on: ubuntu-latest
    env: ${{ secrets }}
    steps:
      - name: Dependabot metadata ğŸ¤–
        id: dependabot_metadata
        uses: dependabot/fetch-metadata@v1.3.6
        with:
          github-token: ${{ secrets.token }}

      - name: Authenticate CLI with PAT ğŸ”
        run: echo "${{ secrets.token }}" | gh auth login --with-token

      - name: Enable auto-merge for Dependabot PRs ğŸ•º
        if: steps.dependabot_metadata.outputs.dependency-type == 'direct:development' && (steps.dependabot_metadata.outputs.update-type == 'version-update:semver-minor' || steps.dependabot_metadata.outputs.update-type == 'version-update:semver-patch')
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
