name: 'Auto Merge PRs'

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment for the workflow'
        default: 'dependabot'
        required: true
        type: string
    secrets:
      dependabot-token:
        description: 'Dependabot token'
        required: true

jobs:
  dependabot:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Dependabot metadata ğŸ¤–
        id: dependabot_metadata
        uses: dependabot/fetch-metadata@v1.2.1
        with:
          alert-lookup: true
          github-token: ${{ secrets.dependabot-token }}

      - name: Authenticate CLI with PAT ğŸ”
        run: echo "${{ secrets.dependabot-token }}" | gh auth login --with-token

      - name: Enable auto-merge for Dependabot PRs ğŸ•º
        if: steps.dependabot_metadata.outputs.dependency-type == 'direct:development' && (steps.dependabot_metadata.outputs.update-type == 'version-update:semver-minor' || steps.dependabot_metadata.outputs.update-type == 'version-update:semver-patch')
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
